version: '3'
services:
  node:
    image: node:8
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /docker/volumes/djyt/node/app:/home/node/app
    ports:
      - "8081:8081"
    command: "npm start"
